// Generated by https://quicktype.io

export interface User {
  id?:       string;
  password: string;
  enabled?:  boolean;
  nombre:   string;
  apellido: string;
  email:    string;
  roles?:    Role[];
  intentos?: number;
  avatar?:   null;
  topt?:     boolean;
  secret?:   null;
}

export interface Role {
  id:     number;
  nombre: string;
}

export enum Aplicacion {
  INDIe = 'INDIe',
}
